# Generated by Django 5.2.9 on 2026-02-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenitybooking',
            name='amenity',
        ),
        migrations.RemoveField(
            model_name='amenitybooking',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='raised_by',
        ),
        migrations.AlterUniqueTogether(
            name='maintenancebill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='maintenancebill',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='host',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='visit_unit',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.DeleteModel(
            name='AmenityBooking',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='MaintenanceBill',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Resident',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
