# Generated by Django 5.2.9 on 2026-03-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socity', '0003_noticerecipient_visitor_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancebill',
            name='bill_date',
            field=models.DateField(blank=True, default=None, help_text='Date the bill was issued/became active. Defaults to billing_month.', null=True),
        ),
    ]
