# Generated by Django 5.2.9 on 2026-03-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socity', '0004_maintenancebill_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancebill',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='True if bill was auto-generated by system. False if manually created by admin.'),
        ),
    ]
