# Generated by Django 5.2.10 on 2026-04-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socity', '0005_maintenancebill_is_auto_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
