from django.db import models
from django.core.exceptions import ValidationError
from core.models import User

# 2. Unit/Flat Details
class Unit(models.Model):
    """Model for storing unit/flat information"""
    UNIT_TYPES = [
        ('1BHK', '1 BHK'),
        ('2BHK', '2 BHK'),
        ('3BHK', '3 BHK'),
        ('4BHK', '4 BHK'),
        ('SHOP', 'Shop'),
        ('OFFICE', 'Office'),
    ]
    
    unit_no = models.CharField(max_length=10, unique=True)
    wing = models.CharField(max_length=5)
    floor = models.IntegerField()
    unit_type = models.CharField(max_length=10, choices=UNIT_TYPES)
    sq_ft = models.DecimalField(max_digits=7, decimal_places=2)
    is_occupied = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['wing', 'floor', 'unit_no']
    
    def __str__(self):
        return f"{self.wing}-{self.unit_no}"


# 3. Resident Profile
class Resident(models.Model):
    """Model for storing resident/owner information"""
    STATUS_CHOICES = [
        ('OWNER', 'Owner'),
        ('TENANT', 'Tenant'),
        ('FAMILY_MEMBER', 'Family Member'),
    ]
    
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='resident_profile')
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, related_name='residents')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    vehicle_no = models.CharField(max_length=20, blank=True, null=True)
    member_count = models.IntegerField(default=1)
    move_in_date = models.DateField()
    move_out_date = models.DateField(blank=True, null=True)
    emergency_contact = models.CharField(max_length=100, blank=True, null=True)
    emergency_phone = models.CharField(max_length=15, blank=True, null=True)
    occupation = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        ordering = ['unit']
    
    def __str__(self):
        return f"{self.user.get_full_name()} - {self.unit}"


# 4. Maintenance Billing
class MaintenanceBill(models.Model):
    """Model for maintenance billing"""
    PAYMENT_STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('PAID', 'Paid'),
        ('OVERDUE', 'Overdue'),
        ('PARTIAL', 'Partial Payment'),
    ]
    
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, related_name='maintenance_bills')
    billing_month = models.DateField()
    bill_date = models.DateField(default=None, null=True, blank=True, help_text="Date the bill was issued/became active. Defaults to billing_month.")
    is_auto_generated = models.BooleanField(default=False, help_text="True if bill was auto-generated by system. False if manually created by admin.")
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    penalty = models.DecimalField(max_digits=7, decimal_places=2, default=0.00)
    status = models.CharField(max_length=20, choices=PAYMENT_STATUS_CHOICES, default='PENDING')
    payment_date = models.DateTimeField(null=True, blank=True)
    payment_mode = models.CharField(max_length=50, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-billing_month']
        unique_together = ['unit', 'billing_month']
    
    def get_effective_bill_date(self):
        """Return the effective bill date - bill_date if set, otherwise billing_month."""
        return self.bill_date if self.bill_date else self.billing_month
    
    def __str__(self):
        return f"{self.unit} - {self.billing_month.strftime('%B %Y')}"


# 5. Visitor Tracking
class Visitor(models.Model):
    """Model for tracking visitors"""
    STATUS_CHOICES = [
        ('IN', 'Entered'),
        ('OUT', 'Exited'),
    ]

    APPROVAL_STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('APPROVED', 'Approved'),
        ('REJECTED', 'Rejected'),
    ]
    
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    email = models.EmailField(blank=True, null=True)
    visit_unit = models.ForeignKey(Unit, on_delete=models.CASCADE, related_name='visitors')
    host = models.ForeignKey(Resident, on_delete=models.SET_NULL, null=True, blank=True)
    purpose = models.CharField(max_length=200)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='IN')
    approval_status = models.CharField(max_length=20, choices=APPROVAL_STATUS_CHOICES, default='PENDING')
    approval_note = models.CharField(max_length=255, blank=True)
    in_time = models.DateTimeField(auto_now_add=True)
    out_time = models.DateTimeField(null=True, blank=True)
    vehicle_no = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        ordering = ['-in_time']
    
    def __str__(self):
        return f"{self.name} - {self.visit_unit}"


# 6. Complaint/Issue Management
class Complaint(models.Model):
    """Model for managing complaints and issues"""
    CATEGORY_CHOICES = [
        ('MAINTENANCE', 'Maintenance Issue'),
        ('WATER', 'Water Problem'),
        ('ELECTRICITY', 'Electricity Problem'),
        ('GAS', 'Gas Problem'),
        ('NOISE', 'Noise Complaint'),
        ('PARKING', 'Parking Issue'),
        ('SECURITY', 'Security Issue'),
        ('OTHER', 'Other'),
    ]
    
    STATUS_CHOICES = [
        ('OPEN', 'Open'),
        ('IN_PROGRESS', 'In Progress'),
        ('RESOLVED', 'Resolved'),
        ('CLOSED', 'Closed'),
    ]
    
    raised_by = models.ForeignKey(Resident, on_delete=models.CASCADE, related_name='complaints')
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    title = models.CharField(max_length=200)
    description = models.TextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='OPEN')
    priority = models.IntegerField(default=1)  # 1=Low, 2=Medium, 3=High
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    resolved_date = models.DateTimeField(null=True, blank=True)
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='assigned_complaints')

    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.title} - {self.get_status_display()}"


# 7. Amenities/Facilities
class Amenity(models.Model):
    """Model for society amenities"""
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    is_available = models.BooleanField(default=True)
    image = models.ImageField(upload_to='amenities/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Amenities"
    
    def __str__(self):
        return self.name


# 8. Amenity Booking
class AmenityBooking(models.Model):
    """Model for amenity reservations"""
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('CONFIRMED', 'Confirmed'),
        ('CANCELLED', 'Cancelled'),
        ('COMPLETED', 'Completed'),
    ]
    
    resident = models.ForeignKey(Resident, on_delete=models.CASCADE)
    amenity = models.ForeignKey(Amenity, on_delete=models.CASCADE, related_name='bookings')
    booking_date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    purpose = models.CharField(max_length=200, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['booking_date']
    
    def __str__(self):
        return f"{self.resident.user.get_full_name()} - {self.amenity.name} - {self.booking_date}"


# 9. Notice/Announcement
class Notice(models.Model):
    """Model for society notices and announcements"""
    PRIORITY_CHOICES = [
        ('LOW', 'Low'),
        ('MEDIUM', 'Medium'),
        ('HIGH', 'High'),
        ('URGENT', 'Urgent'),
    ]
    
    title = models.CharField(max_length=200)
    content = models.TextField()
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES, default='MEDIUM')
    posted_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    posted_date = models.DateTimeField(auto_now_add=True)
    expiry_date = models.DateField(null=True, blank=True)
    image = models.ImageField(upload_to='notices/', blank=True, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-posted_date']
        verbose_name_plural = "Notices"
    
    def __str__(self):
        return self.title

    def is_visible_to(self, user):
        """Global notices are visible to all users; targeted notices require membership."""
        if not user or not user.is_authenticated:
            return False
        return not self.recipients.exists() or self.recipients.filter(user=user).exists()


class NoticeRecipient(models.Model):
    """Optional targeting for notices to selected users."""
    notice = models.ForeignKey(Notice, on_delete=models.CASCADE, related_name='recipients')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notice_recipients')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['notice', 'user']
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.notice.title} -> {self.user.get_full_name() or self.user.username}"


# 10. Payment/Transaction
class Transaction(models.Model):
    """Model for tracking payments and transactions"""
    TRANSACTION_TYPE_CHOICES = [
        ('MAINTENANCE', 'Maintenance Bill'),
        ('OTHER_CHARGE', 'Other Charges'),
        ('REFUND', 'Refund'),
        ('AMENITY_BOOKING', 'Amenity Booking'),
    ]
    
    PAYMENT_MODE_CHOICES = [
        ('CASH', 'Cash'),
        ('CHEQUE', 'Cheque'),
        ('ONLINE', 'Online Transfer'),
        ('UPI', 'UPI'),
    ]
    
    bill = models.ForeignKey(MaintenanceBill, on_delete=models.SET_NULL, null=True, blank=True)
    resident = models.ForeignKey(Resident, on_delete=models.CASCADE, related_name='transactions')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    transaction_type = models.CharField(max_length=20, choices=TRANSACTION_TYPE_CHOICES)
    payment_mode = models.CharField(max_length=20, choices=PAYMENT_MODE_CHOICES)
    reference_no = models.CharField(max_length=100, unique=True)
    transaction_date = models.DateTimeField(auto_now_add=True)
    remarks = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['-transaction_date']
    
    def __str__(self):
        return f"{self.resident.user.get_full_name()} - {self.get_transaction_type_display()} - {self.amount}"


# 11. Staff Profile
class Staff(models.Model):
    """Model for storing staff/maintenance worker information"""
    DESIGNATION_CHOICES = [
        ('SECURITY', 'Security Guard'),
        ('MAINTENANCE', 'Maintenance Worker'),
        ('CLEANER', 'Cleaner'),
        ('GARDENER', 'Gardener'),
        ('SUPERVISOR', 'Supervisor'),
        ('OTHER', 'Other'),
    ]
    
    STATUS_CHOICES = [
        ('ACTIVE', 'Active'),
        ('INACTIVE', 'Inactive'),
        ('ON_LEAVE', 'On Leave'),
    ]
    
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='staff_profile')
    designation = models.CharField(max_length=20, choices=DESIGNATION_CHOICES)
    department = models.CharField(max_length=100, blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='ACTIVE')
    join_date = models.DateField()
    salary = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    aadhar_no = models.CharField(max_length=12, blank=True, null=True, unique=True)
    emergency_contact = models.CharField(max_length=100, blank=True, null=True)
    emergency_phone = models.CharField(max_length=15, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-join_date']
    
    def __str__(self):
        return f"{self.user.get_full_name()} - {self.get_designation_display()}"


# 12. Building Information
class Building(models.Model):
    """Model for storing building information"""
    name = models.CharField(max_length=100, unique=True)
    wing_code = models.CharField(max_length=5, unique=True)
    total_floors = models.IntegerField()
    units_per_floor = models.IntegerField()
    address = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
    
    def __str__(self):
        return self.name


# 13. Notice Read Status (Track which residents have seen notices)
class NoticeRead(models.Model):
    """Model to track which residents have read notices"""
    notice = models.ForeignKey(Notice, on_delete=models.CASCADE, related_name='read_by')
    resident = models.ForeignKey(Resident, on_delete=models.CASCADE)
    read_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['notice', 'resident']
    
    def __str__(self):
        return f"{self.resident.user.get_full_name()} read {self.notice.title}"


# 14. Task Assignment for Staff
class Task(models.Model):
    """Model for assigning maintenance tasks to staff"""
    PRIORITY_CHOICES = [
        ('LOW', 'Low'),
        ('MEDIUM', 'Medium'),
        ('HIGH', 'High'),
        ('URGENT', 'Urgent'),
    ]
    
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('IN_PROGRESS', 'In Progress'),
        ('COMPLETED', 'Completed'),
        ('CANCELLED', 'Cancelled'),
    ]
    
    title = models.CharField(max_length=200)
    description = models.TextField()
    assigned_to = models.ForeignKey(Staff, on_delete=models.CASCADE, related_name='tasks')
    assigned_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='assigned_tasks')
    location = models.CharField(max_length=200, blank=True, null=True)
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES, default='MEDIUM')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    assigned_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateField(blank=True, null=True)
    completed_date = models.DateTimeField(null=True, blank=True)
    remarks = models.TextField(blank=True, null=True)
    complaint = models.ForeignKey(Complaint, on_delete=models.SET_NULL, null=True, blank=True, related_name='tasks')

    class Meta:
        ordering = ['-assigned_date']
    
    def __str__(self):
        return f"{self.title} - {self.get_status_display()}"


# 15. Visitor Pre-Approval by Resident
class VisitorApproval(models.Model):
    """Model for residents to pre-approve or block visitors"""
    STATUS_CHOICES = [
        ('APPROVED', 'Approved'),
        ('BLOCKED', 'Blocked'),
        ('PENDING', 'Pending'),
    ]
    
    resident = models.ForeignKey(Resident, on_delete=models.CASCADE, related_name='visitor_approvals')
    visitor_name = models.CharField(max_length=100)
    visitor_phone = models.CharField(max_length=15, blank=True, null=True)
    purpose = models.CharField(max_length=200)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    valid_from = models.DateField()
    valid_to = models.DateField()
    notes = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.visitor_name} - {self.resident.unit} ({self.get_status_display()})"


# 16. Complaint Status Updates (Track progress on complaints)
class ComplaintUpdate(models.Model):
    """Model to track status updates on complaints"""
    complaint = models.ForeignKey(Complaint, on_delete=models.CASCADE, related_name='updates')
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    status = models.CharField(max_length=20, choices=Complaint.STATUS_CHOICES)
    remarks = models.TextField()
    update_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-update_date']
    
    def __str__(self):
        return f"{self.complaint.title} updated to {self.get_status_display()}"
